### ISSUE TITLE
can i haz a solc version freeze plz :(

### ISSUE THREAD

**Issue by mhhf** [dapphub/k-dss#41]
plz

**Comment by rainbreak** [comment]
A specific reason is so you can figure out pc values for rpow?

**Comment by livnev** [comment]
This should really be a `dapptools` issue: `dapp --use` doesn't work when `dapp` is installed declaratively.

**Comment by asymmetric** [comment]
@livnev `dapp —use` was not the problem, correct?

**Comment by livnev** [comment]
@asymmetric yeah IIRC I was just setting the `DAPPTOOLS` path incorrectly in the nix derivation for the CI, after debugging it for a bit I got `dapp --use` to work: false alarm.
