### ISSUE TITLE
`make` fails with a type error in internal/fs/utils.js

### ISSUE THREAD

**Issue by pirapira** [dapphub/k-dss#50]
The error looks like
```
internal/fs/utils.js:524
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
```

I pasted a a bigger console log at https://gist.github.com/pirapira/cfa3afd6928b98f3171a38a67a98d113

**Comment by pirapira** [comment]
This happens after
```
git clone --branch 0.3 https://github.com/dapphub/klab.git
```

I'll try their master branch.

**Comment by pirapira** [comment]
This problem disappears when I use `master` branch of `klab`.

**Comment by livnev** [comment]
@pirapira We'll change the `klab` readme to just suggest `master`.
